#!/usr/bin/env python3

import subprocess                                       import sys
if len(sys.argv) >2:
    print("Error, Too many Arguments Provided")
elif sys.argv[1]=="license" or "-l":                        with open("LICENSE",'r') as l:
        f=l.read()                                              print(f)
else:                                                       subprocess.run(["python3","src/main.py",sys.argv[1]])
